# Source: jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-docker-cfg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: jx-labs-infra
  data:
  - name: config.json
    key: tf-jx-growing-ant-jenkins-docker-cfg
    version: latest
  template:
    type: Opaque
